### ISSUE TITLE
Error: Cannot find module 'json-markup'

### ISSUE THREAD

**Issue by hikafer** [BurstNeon/burstcoin-faucet#1]
I am not a coder. I tried to start the faucet but i get this error:
```
C:\Users\hikaf\Desktop\burstcoin-faucet-master>node startFaucet.js
module.js:549
    throw err;
    ^

Error: Cannot find module 'json-markup'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\hikaf\Desktop\burstcoin-faucet-master\startFaucet.js:1:80)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by tw-94** [comment]
You have to install the required modules, you have two options (if you added node), 1. you can run from command npm update (installed all required modules) or 2. install all modules successively example for json-markup: npm install json-markup etc. lovely regards
