### ISSUE TITLE
Cannot read property

### ISSUE THREAD

**Issue by hikafer** [BurstNeon/burstcoin-faucet#2]
It seems to be working but when submitting form nothing happens on client side (web)
And in console it says this: 

```
1 | Requested Account: 8027787562746458798
C:\Users\Hikafer\Desktop\Burst\Faucet\burstcoin-faucet-master\startFaucet.js:98
            if (body.errorCode == 5) {
                     ^

TypeError: Cannot read property 'errorCode' of undefined
    at Request._callback (C:\Users\Hikafer\Desktop\Burst\Faucet\burstcoin-faucet-master\startFaucet.js:98:22)
    at self.callback (C:\Users\Hikafer\node_modules\request\request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.init (C:\Users\Hikafer\node_modules\request\request.js:454:17)
    at new Request (C:\Users\Hikafer\node_modules\request\request.js:127:8)
    at request (C:\Users\Hikafer\node_modules\request\index.js:53:10)
    at checkAccount (C:\Users\Hikafer\Desktop\Burst\Faucet\burstcoin-faucet-master\startFaucet.js:92:5)
    at checkWallet (C:\Users\Hikafer\Desktop\Burst\Faucet\burstcoin-faucet-master\startFaucet.js:86:9)
    at C:\Users\Hikafer\Desktop\Burst\Faucet\burstcoin-faucet-master\startFaucet.js:57:17

```

Thanks for help, sorry if they are simple solutions. As said, i am not a coder  :)

**Comment by tw-94** [comment]
No problem, I added a new branch.

> body.errorCode == 5
happens if the wallet isnt right, you can use a online wallet as well or a local wallet (need up to date blockchain).
