### ISSUE TITLE
Cannot read property 'balanceNQT'

### ISSUE THREAD

**Issue by hikafer** [BurstNeon/burstcoin-faucet#3]
Hi, the  "Cannot read property" is fixed, but now i have this new issue.

Tha wallet i am using is this one: http://wallet.burst-coin.es
it is up to date. The only difference is that it's from local machine.
I tried with: localhost:8125, 127.0.0.1:8125 but still not working.
**But with: http://127.0.0.1:8125 it seems to working now**
Faucet: http://faucet.burst-coin.es
```
C:\Users\Hikafer\Desktop\Burst\Faucet\burstcoin-faucet-master\startFaucet.js:98
        amount = satoshiToDecimal(body.balanceNQT);
                                       ^

TypeError: Cannot read property 'balanceNQT' of undefined
    at Request._callback (C:\Users\Hikafer\Desktop\Burst\Faucet\burstcoin-faucet-master\startFaucet.js:98:40)
    at self.callback (C:\Users\Hikafer\node_modules\request\request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.init (C:\Users\Hikafer\node_modules\request\request.js:454:17)
    at new Request (C:\Users\Hikafer\node_modules\request\request.js:127:8)
    at request (C:\Users\Hikafer\node_modules\request\index.js:53:10)
    at getAccountBalance (C:\Users\Hikafer\Desktop\Burst\Faucet\burstcoin-faucet-master\startFaucet.js:92:5)
    at C:\Users\Hikafer\Desktop\Burst\Faucet\burstcoin-faucet-master\startFaucet.js:57:29
    at IncomingMessage.<anonymous> (C:\Users\Hikafer\node_modules\express-recaptcha\dist\index.js:107:21)

C:\Users\Hikafer\Desktop\Burst\Faucet\burstcoin-faucet-master>goto loop
```

**Comment by tw-94** [comment]
Allright, tested with the http://wallet.burst-coin.es and working on systems. Hope that the problems now solved, otherwise feel free to contact me, lovely regards.
